TRUNCATE TABLE "Session"            RESTART IDENTITY CASCADE;
TRUNCATE TABLE "Account"            RESTART IDENTITY CASCADE;
TRUNCATE TABLE "VerificationToken"  RESTART IDENTITY CASCADE;
TRUNCATE TABLE "User"               RESTART IDENTITY CASCADE;