name: Vercel Retry & Notify (frozen)

on:
  # 自動実行は一切しない。必要なら手動起動のみ（それでもジョブは強制スキップ）
  workflow_dispatch:
    inputs:
      note:
        description: "This workflow is frozen (no-op)."
        required: false
        default: "frozen"

# 同時実行の押し込み事故を避けるためにグルーピング
concurrency:
  group: vercel-retry-frozen
  cancel-in-progress: true

# 権限は最小化（念のため読み取りのみに近い形）
permissions:
  contents: read

jobs:
  noop:
    # 常に実行しない（強制スキップ）
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - name: Frozen (No-Op)
        run: echo "This workflow is frozen and does nothing."
